// Mobile App Events Constants

// Outgoing events (from webapp to mobile app)
export const DISPLAY_SETTING = 'DISPLAY_SETTING'
export const GO_OFFLINE = 'GO_OFFLINE'
export const GET_PLAYERCONTENT_JSON = 'GET_PLAYERCONTENT_JSON'
export const DOWNLOAD_REQUESTED = 'DOWNLOAD_REQUESTED'
export const CHAT_BOT_VISIBILITY = 'CHAT_BOT_VISIBILITY'
export const IOS_OPEN_IN_BROWSER = 'IOS_OPEN_IN_BROWSER'
export const TOKEN_OUTGOING = 'TOKEN_OUTGOING'
export const SESSIONID_OUTGOING = 'SESSIONID_OUTGOING'
export const ISAUTHENTICATED_OUTGOING = 'ISAUTHENTICATED_OUTGOING'

// Incoming events (from mobile app to webapp)
export const NAVIGATION_DATA_INCOMING = 'NAVIGATION_DATA_INCOMING'
